# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oz_UqiTtBgLDuD0LNZX2Mo_PfzQBAffO
"""
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor

def analyze_and_forecast():
    df = pd.read_csv('wheat_prices_siyana.csv')
    df['Price'] = df['Price (Rs/Qtl)'].str.replace('Rs. ', '', regex=False).str.replace(',', '', regex=False).astype(float)
    df['Date'] = pd.to_datetime(df['Date'])
    df['MonthName'] = df['Date'].dt.month_name()
    df['DayOfYear'] = df['Date'].dt.dayofyear

    print("______ 2026 MONTHLY MARKET MAXIMUM PRICE FORECAST ______")
    try:
        jan_input_price = float(input("Enter current market price for January 2026 (Rs/Qtl): "))
    except ValueError:
        print("Invalid input. Please enter a numerical value.")
        return
    avg_jan_hist = df[df['MonthName'] == 'January']['Price'].mean()
    scale_factor = jan_input_price / avg_jan_hist

    X = df[['DayOfYear']]
    y = df['Price'] * scale_factor
    model = DecisionTreeRegressor(max_depth=10)
    model.fit(X, y)

    timeline_2026 = pd.date_range(start='2026-01-01', end='2026-06-30')
    predict_df = pd.DataFrame({
        'Date': timeline_2026,
        'DayOfYear': timeline_2026.dayofyear,
        'Month': timeline_2026.month_name()
    })
    predict_df['Predicted_Price'] = model.predict(predict_df[['DayOfYear']])

    print("\n" + "_"*80)
    print(f"{'Month':<15} | {'Predicted Max Price':<20} | {'Expected Peak Window'}")
    print("-" * 80)

    for month in ['January', 'February', 'March', 'April', 'May', 'June']:
        month_data = predict_df[predict_df['Month'] == month]
        if not month_data.empty:
            max_price = month_data['Predicted_Price'].max()
            max_dates = month_data[month_data['Predicted_Price'] == max_price]['Date']

            start_window = max_dates.min().strftime('%d %B')
            end_window = max_dates.max().strftime('%d %B')

            print(f"{month:<15} | Rs. {max_price:<17.2f} | {start_window} to {end_window}")

if __name__ == "__main__":
    analyze_and_forecast()

import pandas as pd
import joblib
from sklearn.tree import DecisionTreeRegressor

df = pd.read_csv('wheat_prices_siyana.csv')

df['Price'] = df['Price (Rs/Qtl)'].str.replace('Rs. ', '', regex=False).str.replace(',', '', regex=False).astype(float)
df['Date'] = pd.to_datetime(df['Date'])
df['DayOfYear'] = df['Date'].dt.dayofyear
df['MonthName'] = df['Date'].dt.month_name()

X = df[['DayOfYear']]
y = df['Price']
model = DecisionTreeRegressor(max_depth=10)
model.fit(X, y)
jan_ref_price = df[df['MonthName'] == 'January']['Price'].mean()
joblib.dump(model, 'wheat_model.joblib')
joblib.dump(jan_ref_price, 'jan_ref.joblib')

print("Model and Reference Price saved successfully!")

model.score(X ,y)

print("Installing dependencies...")

with open('app.py', 'w') as f:
    f.write('''
import joblib
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
try:
    model = joblib.load('wheat_model.joblib')
    jan_ref = joblib.load('jan_ref.joblib')
except:
    st.error("Model files not found. Please run the training cell first.")
    st.stop()

st.set_page_config(page_title="Siyana Wheat Price Prediction 2026(jan-june)", layout="wide")
st.title("🌾Siyana Wheat Price Prediction 2026(jan-june)")
st.markdown("This forecast predicts the **Maximum Price** and the **Peak Window** for the first half of 2026.")

jan_input = st.sidebar.number_input("Current January Price (Rs/Qtl)", value=float(jan_ref))
scale_factor = jan_input / jan_ref
dates = pd.date_range(start="2026-01-01", end="2026-06-30")
df_2026 = pd.DataFrame({
    'Date': dates,
    'DayOfYear': dates.dayofyear,
    'Month': dates.month_name()
})
predictions = model.predict(df_2026[['DayOfYear']])
df_2026['Price'] = predictions * scale_factor
results = []
months_to_forecast = ["January", "February", "March", "April", "May", "June"]

for m in months_to_forecast:
    m_df = df_2026[df_2026['Month'] == m]

    if not m_df.empty:
        max_p = m_df['Price'].max()
        max_dates = m_df[m_df['Price'] == max_p]['Date']

        start_window = max_dates.min().strftime('%d %b')
        end_window = max_dates.max().strftime('%d %b')
        if start_window == end_window:
            window_text = start_window
        else:
            window_text = f"{start_window} to {end_window}"

        results.append({
            "Month": m,
            "Max Price (Rs)": f"₹{max_p:,.2f}",
            "Expected Peak Window": window_text
        })
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Monthly Maximums")
    st.table(pd.DataFrame(results))

with col2:
    st.subheader("Price Trend (Jan-Jun 2026)")
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df_2026['Date'], df_2026['Price'], color='green', linewidth=2)
    ax.fill_between(df_2026['Date'], df_2026['Price'], alpha=0.1, color='green')
    ax.set_ylabel("Price (Rs)")
    plt.xticks(rotation=45)
    st.pyplot(fig)
''')
import subprocess
import time
print("Starting Streamlit...")
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"])
time.sleep(5)
print("Creating Tunnel... Click the link below when it appears!")


import os
os.system("streamlit run app.py &")
